# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f552a35588fa19c1c6e0f143874f9d7e96cecb2bb2e8615b2f36abfb2d1d554309ef253712c8a2c5d360fc710d32aa5d88b76d1c11876a52806011d3d6e8f05

test:
  secret_key_base: 5797f80f148edb3b80efa48cc009a6a77e7c3d16a9cc73035e472cac31da387a1b7427c3ccd6f383b299bc0e0d890946f3b5fee5aaf1743983b0c82d1f755646

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
